//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mediachase.Cms.Website.Templates.Default.Modules {
    
    
    public partial class CheckoutWizardModule {
        
        /// <summary>
        /// CheckoutWizard control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Wizard CheckoutWizard;
        
        /// <summary>
        /// ShippingAddressStep control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.WizardStep ShippingAddressStep;
        
        /// <summary>
        /// CheckoutShippingAddress control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Mediachase.Cms.Website.Templates.Default.Modules.CheckoutAddressModule CheckoutShippingAddress;
        
        /// <summary>
        /// ShippingOptionsStep control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.WizardStep ShippingOptionsStep;
        
        /// <summary>
        /// CheckoutShipping control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Mediachase.Cms.Website.Templates.Default.Modules.CheckoutShippingModule CheckoutShipping;
        
        /// <summary>
        /// PaymentStep control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.WizardStep PaymentStep;
        
        /// <summary>
        /// CheckoutPayment control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Mediachase.Cms.Website.Templates.Default.Modules.CheckoutPaymentModule CheckoutPayment;
        
        /// <summary>
        /// FinalStep control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.WizardStep FinalStep;
        
        /// <summary>
        /// CheckoutConfirm control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Mediachase.Cms.Website.Templates.Default.Modules.CheckoutConfirmModule CheckoutConfirm;
    }
}
